[project]
name = "ehdg_pupil_detector"
version = "4.0.0"
authors = [
  { name="Zaw Lin Tun", email="zawlintun1511@gmail.com" },
]
description = "Python Library for Pupil Detector of Eye Health Diagnostic Group"
readme = "README.md"
dependencies = ["setuptools>=61.0", "opencv-python>=4.8.1.78", "scipy>=1.11.3", "numpy>=1.26.1", "commentjson", "ehdg_tools>=4.2.3", "numpy"]
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]

[project.scripts]
opmtrack = "ehdg_pupil_detector.opmtrack:main"

[project.urls]
"Homepage" = "https://github.com/jtur044/ehdg_pupil_detector"
"Bug Tracker" = "https://github.com/jtur044/ehdg_pupil_detector/issues"

[build-system]
requires = ["setuptools>=61.0", "opencv-python>=4.8.1.78", "scipy>=1.11.3", "numpy>=1.26.1", "commentjson", "ehdg_tools>=4.2.3", "numpy"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
ehdg_pupil_detector = ["*"]
