[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "friendsbalt"
version = "0.1.1"
authors = [
  { name="Joel Hammer", email="jhammer@friendsbalt.org" },
]
description = "A short description of your package"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/yourusername/friendsbaltcs"
"Bug Tracker" = "https://github.com/yourusername/friendsbaltcs/issues"

[tool.hatch.build.targets.wheel]
packages = ["src/friendsbalt"]