[tool.poetry]
version = "1.7.3"
name = "MainShortcuts"
description = "Simplifying Python Built-in Commands"
authors = [ "MainPlay TG <xbox.roman6666666666@gmail.com>",]
readme = "README.md"
repository = "https://github.com/MainPlay-TG/MainShortcuts.py"
packages = [
    { include = "MainShortcuts", from = "src" },
]

[tool.poetry.scripts]
MS-getCore = "MainShortcuts.script:getCore"
MS-getCoreMini = "MainShortcuts.script:getCore"
MS-jsonC = "MainShortcuts.script:jsonCompress"
MS-jsonP = "MainShortcuts.script:jsonPretty"
MS-mkdir = "MainShortcuts.script:mkdir"

[tool.poetry.dependencies]
python = "^3.7"

[build-system]
requires = [ "poetry-core",]
build-backend = "poetry.core.masonry.api"
