[project]
name = "jellyfaas"
version = "0.0.2"
description = "A client for interacting with the JellyFAAS API"
authors = [
    { name = "Caleb Hartshorn", email = "caleb@platform48.com" }
]
license = { file = "LICENSE" }
dependencies = [
    "requests",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
dynamic = ["version"]

[tool.hatch.build]
include = [
    "src/jellyfaas",
]
