[project]
name = "oracle-data-studio"
description = "Python client for Oracle Data Studio Database Service"
version = "1.0.1"
readme = "README.md"
license = {file = "LICENSE.txt"}
requires-python = ">=3.6"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: UPL :: Apache 2.0",
    "Operating System :: OS Independent",
]
keywords = ["Oracle database", "ORDS", "Oracle database actions"]

[build-system]
requires = ["requests", "setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages =["adp"]
include-package-data=false
license-files = ['LICEN[CS]E*', 'COPYING*', 'NOTICE*', 'AUTHORS*', 'THIRD_PARTY_LICEN[CS]E*']
