[tool.poetry]
name = "canonicalwebteam-store-base"

version = "1.1.0"
description = "An application base for all stores"
authors = ["Canonical Webteam <webteam@canonical.com>"]
license = "GPL3"
readme = "README.md"
packages = [{include = "canonicalwebteam"}]

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
"canonicalwebteam.flask-base" = "^2.0.0"
"canonicalwebteam.store-api" = "^4.8.0"
Flask-WTF = "^1.0.1"
pipenv = "^2022.12.19"
python-dotenv = "^0.20.0"
responses = "^0.22.0"
talisker = "^0.21.3"
flake8 = "^6.0.0"

[tool.poetry.group.dev.dependencies]
Flask-Testing = "^0.8.1"
freezegun = "^0.3.4"
tox = "^4.4.11"
black = "^23.9.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
 
