[tool.poetry]
name = "glagos-flowai"
version = "0.3.0"
description = "A CLI tool for multi-agent LLM tasks"
authors = ["Gabriel Lagos <gabriellagos@ramenbaby.com.au>"]
readme = "README.md"
packages = [{include = "flowai"}]
include = [
    "flowai/template-commit-message.txt",
    "flowai/template-pull-request.txt"
]

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
requests = "^2.31.0"
python-dotenv = "^1.0.0"
openai = "^1.38.0"
anthropic = "^0.31.2"
typer = "^0.12.3"
rich = "^13.5.2"
questionary = "^1.10.0"
groq = "^0.4.2"
google-generativeai = "^0.3.2"
pyperclip = "^1.8.2"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
flowai = "flowai.main:app"
