[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "populisengineagentsmanagementdb"
version = "0.1.4"
description = "Management CRUD in MongoDB"
authors = [
    { name = "Grenne", email = "grenne@populisrh.com" }
]
requires-python = ">=3.6"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = ["pymongo"]

