[tool.poetry]
name = "neo4j-cypher"
version = "0.1.0"
description = "Natural language interface for a Neo4j graph database"
authors = [
    "Tomaz Bratanic <tomaz.bratanic@neo4j.com>",
]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
numpy = ">=1.26.0,<2.0.0"
langchain = "^0.2.13"
neo4j = "^5.23.1"
openai = "^1.40.6"
langchain-openai = "^0.1.21"
langchain-community = "^0.2.12"
langchain-aws = "^0.1.16"
python-dotenv = "^1.0.1"

[tool.poetry.group.dev.dependencies]
langchain-cli = ">=0.0.21"

[tool.langserve]
export_module = "neo4j_cypher"
export_attr = "chain"

[tool.templates-hub]
use-case = "query"
author = "Neo4j"
integrations = ["Neo4j", "OpenAI"]
tags = ["search", "graph-database"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
