[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "iisi-python"
description = ''
readme = "README.md"
requires-python = ">=3.11"
license = "MIT"
keywords = []
authors = [
  { name = "Iimiva", email = "iiro.sinisalo@isinisalo.com" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
  "punq",
  "authoritah"
]
dynamic = ["version"]

[tool.hatch.build]
sources = ["src"]
exclude = [
  "src/tests",
  ".pypirc",
  ".pylintrc",
  ".gitignore",
  ".vscode/**",
  "pytest.ini",
  "pyproject.toml",
  "release.sh",
]

[tool.hatch.build.targets.wheel]
packages = ["src/iisi"]

[project.urls]
Documentation = "https://github.com/Iimiva/iisi#readme"
Issues = "https://github.com/Iimiva/iisi/issues"
Source = "https://github.com/Iimiva/iisi"

[tool.hatch.version]
path = "src/iisi/__about__.py"

[tool.hatch.envs.default]
dependencies = [
  "pytest",
  "pytest-cov",
]
[tool.hatch.envs.default.scripts]
cov = "pytest --cov-report=term-missing --cov-config=pyproject.toml --cov=iisi --cov=tests {args}"
no-cov = "cov --no-cov {args}"

[[tool.hatch.envs.test.matrix]]
python = ["311"]

[tool.coverage.run]
branch = true
parallel = true
omit = [
  "src/iisi/__about__.py",
]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]
