[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "wownlp"
version = "0.0.1-7"
authors = [
  { name="minskiter", email="minskiter@gmail.com" },
]
description = "Wow! Fast NLP."
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "tqdm>=4.0.0"
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/minskiter/wownlp"
Issues = "https://github.com/minskiter/wownlp/issues"