[tool.poetry]
name = "tma-authenticator"
version = "0.0.6.1"
description = "Verifying telegram user token."
authors = ["Ivan Kochelorov <imkochelorov@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11.9"
fastapi = "^0.112.0"
bson = "^0.5.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
