[tool.poetry]
name = "clarity-common"
version = "1.0.36"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pydantic="2.4.*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
