[project]
name = "marhex_validators"
version = "2.0.2"
authors = [
  { name="Mehran MarHex", email="mehran.marhex@gmail.com" },
]
description = "Some Custom Validators"
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
GitHub = "https://github.com/mehran-marhex"
