[tool.poetry]
name = "h3-toolkit"
version = "0.2.1"
description = ""
authors = ["Huang SyuanBo <godspeed88168@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
polars = "^1.2.0"
geopandas = "^1.0.1"
h3ronpy = "^0.21.0"
aiohttp = "^3.9.5"


[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.5"
pytest = "^8.3.2"
pytest-cov = "^5.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
