[tool.poetry]
name = "geocraft"
version = "0.3.0"
description = "Python library for Geo & WebGIS."
authors = ["Shangjin Tang <shangjin.tang@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.32.3"


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
geoccoord-convert = "geocraft._scripts.coord_convert:main"
parse-baidumap = "geocraft._scripts.parse_baidumap:main"
